name: 'App Infra deploy to azure'

on:
  push:
    branches: [ "main" ]  

env:
  ARM_CLIENT_ID: ${{secrets.CLIENT_ID}}
  ARM_CLIENT_SECRET: ${{secrets.CLIENT_SECRET}}
  ARM_TENANT_ID: ${{secrets.TENANT_ID}}
  ARM_SUBSCRIPTION_ID: ${{secrets.SUBSCRIPTION_ID}}  
  ROOT_PATH_TERRAFORM: '${{ github.workspace }}/src/terraform/app/'

jobs:
  terraform_plan:
    name: 'Terraform plan'
    runs-on: ubuntu-latest    
    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1
   
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Terraform Init
      run: terraform init
      working-directory: ${{ env.ROOT_PATH_TERRAFORM }}

    - name: Terraform Plan
      run: terraform plan
      working-directory: ${{ env.ROOT_PATH_TERRAFORM }}

  terraform_apply:
    name: 'Terraform apply'
    runs-on: ubuntu-latest
    needs: [ terraform_plan ]
    environment: healthmed
    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Terraform Init
      run: terraform init
      working-directory: ${{ env.ROOT_PATH_TERRAFORM }}

    - name: Terraform apply
      run: terraform apply --auto-approve
      working-directory: ${{ env.ROOT_PATH_TERRAFORM }}
